version: 2.1

orbs:
  my-inline-orb: &my_inline_orb
    description: "An inline orb for learning purposes that echoes a provided name."
    inputs:
      name:
        type: string
        description: "The name to be echoed."
    jobs:
      echo_name_job:
        docker:
          - image: cimg/base:stable
        steps:
          - run:
              name: Echo the provided name
              command: echo "Hello, $NAME"

workflows:
  example_workflow:
    jobs:
      - my-inline-orb/echo_name_job:
          name: "CircleCI User"